on:
  push:
    branches:
      - "main"

jobs:
  localhost-check:
    runs-on: ubuntu-latest
    name: "Localhost Check"
    steps:
      - uses: actions/checkout@v3
      - uses: mattsb42/not-grep@master
        with:
          debug: true